import Navbar from '@/layout/navbar';
import ProfilePic from '@/ui/profile-pic';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from './layout/footer';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} items-center justify-center antialiased`}
      >
        <Navbar />
        <div className="mt-section md:mt-section-md mx-auto w-full md:w-9/10 px-content-sm md:px-0">
          {/* Navbar placeholder removed */}
          <div className="p-desktop flex flex-col items-center justify-center md:hidden">
            <ProfilePic
              className="h-40 w-40 rounded-full object-contain"
              width={160}
              height={160}
            />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
