import Navbar from '@/layout/navbar';
import ProfilePic from '@/ui/profile-pic';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from './layout/footer';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} items-center justify-center antialiased`}
      >
        <div className="mx-auto w-9/10">
          <div className="p-desktop gap-section flex flex-row items-center justify-center">
            <div className="flex basis-1/2 items-center justify-start">
              <ProfilePic />
            </div>
            <div className="flex basis-1/2 items-center justify-center">
              <Navbar />
            </div>
          </div>
          {children}
          <Footer />  
        </div>
      </body>
    </html>
  );
}
