import Navbar from '@/layout/navbar';
import ProfilePic from '@/ui/profile-pic';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className='flex flex-row justify-around items-center p-desktop'>
          <ProfilePic />
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
